<h1 align = "center" style = "color :blue">Projet Final de formation de la bibliothèque Pandas (Le projets consiste a analyser des donnees fournis par une université)</h1>

In [120]:
import pandas as pd

## Objectif

Réaliser une analyse complète de données universitaires en utilisant **Pandas uniquement** pour toutes les opérations de traitement et d'analyse.

Vous disposez de 5 fichiers CSV :

- `students.csv` : informations sur les étudiants
- `courses.csv` : informations sur les matières
- `grades.csv` : notes obtenues
- `attendance.csv` : assiduité par semestre
- `exams.csv` : informations sur les examens


## Partie 1 : Découverte des données

Pour chaque fichier :

1. Importer le CSV.
2. Afficher les premières et dernières lignes.
3. Afficher le nombre de lignes et de colonnes.
4. Afficher les noms des colonnes.
5. Examiner les types de données.
6. Produire un résumé statistique.
7. Identifier les valeurs manquantes.
8. Identifier les doublons.

### A) - Importation des fichier csv

In [121]:
Etudiant = pd.read_csv("data/students.csv") # importation des infos sur l'etudiant 

cours =pd.read_csv("data/courses.csv") # Les infos sur les matiere de chaque etudiant

notes_obtenues = pd.read_csv("data/grades.csv") # Information sur les notes des etudiants

assidute = pd.read_csv("data/attendance.csv") # Assidute de l'etudiant par semestre

examen = pd.read_csv("data/exams.csv") # Informations sur les examens

### B) - Affichage des premières et dernières lignes. des data

#### a) - Information des etudiants

In [122]:
Etudiant.head() # affiche les Premiere lignes

  student_id     nom    prenom   age sexe                  filiere niveau
0    ETU1000  Mensah     Koffi  20.0    M   Logistique & Transport     L3
1    ETU1001  Agbeko  Akossiwa  24.0    M  Informatique & Systèmes     L2
2    ETU1002     Doe       Afi  25.0    F   Logistique & Transport     L1
3    ETU1003  Amegan     Dodzi   NaN    F         Génie Électrique     L2
4    ETU1004  Amegan    Mawuli  18.0    M            IA & Big Data     L1

In [123]:
Etudiant.tail() # affiche les derniere lignes

    student_id      nom  prenom   age sexe                  filiere niveau
795    ETU1795    Adjei     Ama  23.0    F         Génie Électrique     L3
796    ETU1796  Assogba    Sena  26.0    M         Génie Électrique     L3
797    ETU1797   Amegan  Mawuli  19.0    M  Informatique & Systèmes     L3
798    ETU1798   Lawson   Eyram  19.0    F              Génie Civil     L3
799    ETU1799   Amegan  Mawuli   NaN    M              Génie Civil     L2

In [124]:
#  1 - Nombre de ligne et colonne dans le Dataframe Etudiant
Etudiant.shape

(800, 7)

In [125]:
# 2- Afficher les noms des colonnes.

Etudiant.columns

Index(['student_id', 'nom', 'prenom', 'age', 'sexe', 'filiere', 'niveau'], dtype='object')

In [78]:
# 3 ) - Examiner les types de données.
Etudiant.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  800 non-null    object
 1   nom         800 non-null    object
 2   prenom      800 non-null    object
 3   age         788 non-null    float64
 4   sexe        792 non-null    object
 5   filiere     800 non-null    object
 6   niveau      800 non-null    object
dtypes: float64(1), object(6)
memory usage: 43.9+ KB

In [79]:
# On remaque la colones des ages a pout types float ==> (impossible donc a corriger)

In [80]:
Etudiant.describe() # 4 - )Resume statistques

              age
count  788.000000
mean    21.446701
std      2.855424
min     17.000000
25%     19.000000
50%     21.000000
75%     24.000000
max     26.000000

In [81]:
Etudiant.isnull().sum() # la colonne age  a 12 notes manquantes

student_id     0
nom            0
prenom         0
age           12
sexe           8
filiere        0
niveau         0
dtype: int64

In [82]:
# Verifications des doucblons
Etudiant.duplicated().sum() #==> 0 doublons

np.int64(0)

#### b) - Information sur les matiere

In [83]:
cours.head() #  affiche les premieres lignes

  course_id        matiere  credits semestre
0    MAT101  Mathématiques        4       S1
1    PHY101       Physique        3       S1
2   PROG101  Programmation        5       S1
3   STAT101   Statistiques        4       S1
4    ANG101        Anglais        2       S1

In [84]:
cours.tail() #  affiche les dernieres lignes

  course_id        matiere  credits semestre
5   DATA101   Data Science        5       S2
6    ALG101  Algorithmique        4       S2
7   ELEC101    Électricité        3       S2
8   GEST101        Gestion        2       S2
9   PROJ101         Projet        4       S2

In [85]:
#  1 - Nombre de ligne et colonne dans le Dataframe contenat les cours
cours.shape  #on a au total 10 cours

(10, 4)

In [86]:
# 2- Afficher les noms des colonnes.

cours.columns

Index(['course_id', 'matiere', 'credits', 'semestre'], dtype='object')

In [87]:
# 3 ) - Examiner les types de données.
cours.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   course_id  10 non-null     object
 1   matiere    10 non-null     object
 2   credits    10 non-null     int64
 3   semestre   10 non-null     object
dtypes: int64(1), object(3)
memory usage: 452.0+ bytes

In [88]:
cours.describe() # 4 - )Resume statistques

         credits
count  10.000000
mean    3.600000
std     1.074968
min     2.000000
25%     3.000000
50%     4.000000
75%     4.000000
max     5.000000

In [89]:
cours.isnull().sum()   ## Pas de valeur manquante dans chacuns des colonnes

course_id    0
matiere      0
credits      0
semestre     0
dtype: int64

In [90]:
# Verifications des doucblons
cours.duplicated().sum() #  ==> 0 doublons

np.int64(0)

#### c) - Information sur les notes des etudiants

In [91]:
notes_obtenues.head()   # affiche les premieres lignes

  student_id course_id   note
0    ETU1000    MAT101   6.03
1    ETU1000    PHY101   6.54
2    ETU1000   PROG101   8.00
3    ETU1000   STAT101  10.48
4    ETU1000    ANG101   8.31

In [92]:
notes_obtenues.tail()   # affiche les dernieres lignes

     student_id course_id   note
7995    ETU1799   DATA101  11.12
7996    ETU1799    ALG101  14.30
7997    ETU1799   ELEC101  15.23
7998    ETU1799   GEST101  15.48
7999    ETU1799   PROJ101  16.37

In [93]:
notes_obtenues.shape ## 8000 note pour 3 colonne

(8000, 3)

In [94]:
notes_obtenues.columns

Index(['student_id', 'course_id', 'note'], dtype='object')

In [95]:
notes_obtenues.info()  # Les notes sont imcomplets il existe donc des notes manquantes dans la colone note (voir ->donnes de infos)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  8000 non-null   object
 1   course_id   8000 non-null   object
 2   note        7870 non-null   float64
dtypes: float64(1), object(2)
memory usage: 187.6+ KB

In [96]:
notes_obtenues.describe() #Resume statistique

              note
count  7870.000000
mean     11.902784
std       3.345841
min       0.000000
25%       9.620000
50%      11.860000
75%      14.220000
max      20.000000

In [97]:
        # Valeuer manquantes :
notes_obtenues.isnull().sum() # ==> La colonnnes de note a 130 notes manquantes

student_id      0
course_id       0
note          130
dtype: int64

In [98]:
# Verifications des doublons
notes_obtenues.duplicated().sum()  # 0  doublons

np.int64(0)

#### d) - information sur l'assiduté    de l'etudiant par semestre

In [99]:
assidute.head()   # affiche les premieres lignes

  student_id semestre  taux_presence  absences  retards
0    ETU1000       S1          88.22         6        3
1    ETU1000       S2          79.11        10        6
2    ETU1001       S1          98.29         1        2
3    ETU1001       S2          92.43         4        4
4    ETU1002       S1          77.95        11        1

In [100]:
assidute.tail()   # affiche les dernieres lignes

     student_id semestre  taux_presence  absences  retards
1595    ETU1797       S2          79.05        10        1
1596    ETU1798       S1          92.19         4        2
1597    ETU1798       S2          72.55        14        2
1598    ETU1799       S1          90.08         5        1
1599    ETU1799       S2          72.99        14        4

In [106]:
assidute.shape #1600 ligne pour 5 colonnes

(1600, 5)

In [107]:
assidute.columns

Index(['student_id', 'semestre', 'taux_presence', 'absences', 'retards'], dtype='object')

In [108]:
assidute.info() # d'apres info ==>la colonnes taux_presence a des informations manquan

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1600 entries, 0 to 1599
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   student_id     1600 non-null   object
 1   semestre       1600 non-null   object
 2   taux_presence  1585 non-null   float64
 3   absences       1600 non-null   int64
 4   retards        1600 non-null   int64
dtypes: float64(1), int64(2), object(2)
memory usage: 62.6+ KB

In [109]:
assidute.describe() #Resumer statistique de l'assidute des etudiants

       taux_presence     absences      retards
count    1585.000000  1600.000000  1600.000000
mean       82.107754     8.941875     2.553125
std        11.364506     5.675485     1.603133
min        46.320000     0.000000     0.000000
25%        74.370000     5.000000     1.000000
50%        82.540000     9.000000     2.000000
75%        90.780000    13.000000     3.000000
max       100.000000    27.000000    10.000000

In [110]:
assidute.isnull().sum() ## ==> La colonne taux_precesenc a 15 informations manquantes

student_id        0
semestre          0
taux_presence    15
absences          0
retards           0
dtype: int64

In [111]:
# Verifications des doucblons
assidute.duplicated().sum() # ==> zero doublons

np.int64(0)

#### e) - Informations sur les examens

In [112]:
examen.head()   # affiche les premieres lignes

  course_id date_examen     session    salle  nombre_candidats
0    MAT101  2025-06-02       Matin  Salle D                44
1    PHY101  2025-06-05       Matin  Salle A                86
2   PROG101  2025-06-08       Matin  Salle C                61
3   STAT101  2025-06-11  Après-midi  Salle A                47
4    ANG101  2025-06-14       Matin  Salle C                79

In [113]:
examen.tail()   # affiche les dernieres lignes

  course_id date_examen     session    salle  nombre_candidats
5   DATA101  2025-06-17  Après-midi  Salle D                85
6    ALG101  2025-06-20       Matin  Salle C                83
7   ELEC101  2025-06-23  Après-midi  Salle C                81
8   GEST101  2025-06-26  Après-midi  Salle C                82
9   PROJ101  2025-06-29       Matin  Salle C                47

In [114]:
examen.shape # 10 lignes pour 5 colonnes

(10, 5)

In [115]:
examen.columns

Index(['course_id', 'date_examen', 'session', 'salle', 'nombre_candidats'], dtype='object')

In [116]:
examen.info() # => Aucun souci avec ce dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   course_id         10 non-null     object
 1   date_examen       10 non-null     object
 2   session           10 non-null     object
 3   salle             10 non-null     object
 4   nombre_candidats  10 non-null     int64
dtypes: int64(1), object(4)
memory usage: 532.0+ bytes

In [117]:
examen.describe() # Resume statistiques

       nombre_candidats
count         10.000000
mean          69.500000
std           17.665094
min           44.000000
25%           50.500000
50%           80.000000
75%           82.750000
max           86.000000

In [118]:
# Valeur manquantes ==> AUCUNE
examen.isnull().sum()

course_id           0
date_examen         0
session             0
salle               0
nombre_candidats    0
dtype: int64

In [119]:
# Verifications des doublons
examen.duplicated().sum() #==> 0 doublons

np.int64(0)

## Partie 2 : Nettoyage

Nettoyer les données et expliquer les décisions prises.

Vous devez notamment :

- traiter les valeurs manquantes ;
- vérifier les doublons ;
- corriger les types de données si nécessaire ;
- vérifier les valeurs incohérentes ;
- uniformiser les données textuelles ;
- convertir les dates correctement.

In [ ]:
# A faire