In [1]:
import pandas as pd

## En résumé

   <p> Il existe deux méthodes pour sélectionner précisément des éléments au sein d’un data frame : </p>

        La méthode.iloc permet de sélectionner à partir des indices. La syntaxe est : 
        mon_dataframe.iloc[ indice(s) ligne ,  indice(s) colonne ]  .

        La méthode.loc permet de sélectionner à partir de conditions et des noms de colonnes. La syntaxe est : 
       .loc[ condition sur les lignes ,  colonne(s) ]  .

    La condition sur les lignes est une condition qui va être testée sur chaque ligne. Une ligne est 
    conservée dans le processus de sélection si elle satisfait à cette condition.
    Cette condition peut être une conjonction de plusieurs conditions séparées par des "et" logiques (& ) ou des "ou" logiques (| ).

    Les index sont des valeurs qui sont associées intrinsèquement à chaque ligne.
    Si on effectue un tri ou toute autre opération, une ligne, quelle que soit sa position dans le data frame, 
    aura toujours le même index. Il est possible de réinitialiser ce dernier via la méthode  .reset_index .

    La méthode.loc peut être également utilisée pour modifier la partie du data frame sélectionnée

## Probleme

### Contexte

Certaines demandes ont été spécifiquement formulées par le responsable du service Prêt de notre établissement. 
Il souhaite que vous puissiez appliquer les traitements nécessaires pour lui donner des réponses précises.
    
#### Consignes


## Filtrez les données du dataframe

Nous allons à présent aller un peu plus loin dans la manipulation de nos prêts bancaires. Les demandes suivantes ont été formulées par le responsable du service prêt de notre établissement :

    - Le taux d’endettement autorisé est de 35%. Pourriez vous me communiquer le nombre de personnes ayant dépassé ce seuil ?
    - Même question, mais cette fois ci uniquement sur l’agence Parisienne
    - Pour faciliter le traitement d’éventuelles futures demandes de prêts, pourriez vous ajouter une variable nommée risque qui nous permettrait            d’identifier les clients risqués facilement
    - Combien de prêts automobiles ont été accordés ? Quel est le coût total moyen de ces derniers ?
    - Quel est le bénéfice mensuel total réalisé par l’agence Toulousaine ?

Vous allez devoir mettre en application l’ensemble des processus de sélection présentés ci-dessus pour répondre à ces différentes demandes.

## Solution

In [2]:
prets= pd.read_csv("Donnes_Banques.csv")
prets.head()

,identifiant,ville,CP,revenu,remboursement,duree,type,taux_interet,taux_endete,cout_total,benefices
0,0,TOULOUSE,31100,3669.0,1130.05,240,immobilier,1.168,30.80,271212.0,131.99
1,1,PARIS,75009,5310.0,240.00,64,automobile,3.701,4.52,15360.0,23.69
2,1,PARIS,75009,5310.0,1247.85,300,immobilier,1.173,23.50,374355.0,182.97
3,2,MARSEILLE,13010,1873.0,552.54,240,immobilier,0.972,29.50,132609.6,53.71
4,3,MARSEILLE,13010,1684.0,586.03,180,immobilier,1.014,34.80,105485.4,44.57

#### (1) Le taux de personnes ayant depasser ce seuil  (35 %)

In [3]:
data = prets.loc[prets["taux_endete"]> 35 , :]
nombrepersonne = data.shape[0]
nombrepersonne

58

In [4]:
## On trouve 58 personne qui on leur taux d'endetement au dessuis de 35 %

#### (2) Même question, mais cette fois ci uniquement sur l’agence Parisienne

In [5]:
data = prets[(prets["taux_endete"]>35) & (prets["ville"] == "PARIS")]
data.shape[0]

16

In [6]:
           # DEUXIEME METHODE EN UTILISANT LOC 

data = prets.loc[(prets["taux_endete"] >35) & (prets["ville"] == "PARIS"), :]
data.shape[0]

16

In [7]:
                                        # conclusion
# On trouve 16 pres opres de l'agence parisiennes qui on des clients dont leur taux d'endetement est au dessuis de 35%

#### (3)  Ajout du variable risque pour permettre d'identifier les clients risqués facilement


<p> Pour faciliter le traitement d éventuelles futures demandes de prêts, pourriez vous ajouter une variable nommée<br>
risque qui aurait pour valeur Oui si le client est risqué (taux d’endettement > 35%), Non sinon.
Pour se faire, je vous conseille de créer la variable 
risque en l'initialisant à Non (ou Oui, à votre préférence) et de ne modifier que les lignes concernées par la valeur inverse :

In [8]:
prets["risque"] = "NON" # initialisation de la variable risque en NON
prets.loc[prets["taux_endete"]>35, "risque"] = "OUI"
x = prets.loc[prets["taux_endete"] > 35 , ]
x.head()

,identifiant,ville,CP,revenu,remboursement,duree,type,taux_interet,taux_endete,cout_total,benefices,risque
7,6,LYON,69008,1867.0,711.33,240,immobilier,1.196,38.1,170719.2,85.08,OUI
8,7,NICE,6000,5486.0,2956.95,300,immobilier,1.184,53.9,887085.0,437.63,OUI
10,9,MARSEILLE,13012,1386.0,612.61,180,immobilier,1.284,44.2,110269.8,58.99,OUI
15,14,TOULOUSE,31400,2413.0,1334.39,300,immobilier,1.154,55.3,400317.0,192.49,OUI
21,20,LYON,69001,3318.0,1237.61,240,immobilier,1.148,37.3,297026.4,142.08,OUI

#### (4)Combien de prêts automobiles ont été accordés ? Quel est le coût total moyen de ces derniers

#####  A -) Nombre total de pret accorder

In [13]:
# Supposons que le clien a droit au prets lorsque sont taut d'endetement <35 et faisont le taff?
SommeAuto = prets.loc[prets["type"] == "automobile",].shape[0]

print("--------------------------------------------------------------")
print(f" Nombre totale de pret accorde : {SommeAuto} personne ")
print("--------------------------------------------------------------")

--------------------------------------------------------------
 Nombre totale de pret accorde : 16 personne
--------------------------------------------------------------

##### B - ) Le coût total moyen de ces derniers

In [10]:
CoutMoyenne= prets.loc[prets["type"] == "automobile", "cout_total"].mean()

print("--------------------------------------------------------------")
print(f"  Cout total moyen de ces derniers : {CoutMoyenne} Euros")
print("--------------------------------------------------------------")

--------------------------------------------------------------
  Cout total moyen de ces derniers : 13665.0 Euros
--------------------------------------------------------------

#### (4) Quel est le bénéfice mensuel total réalisé par l’agence Toulousaine ?

In [11]:
# cela revient a calculer la somme de benefices realiser par l'agence toulousaine
Benefice_Toulouse = round(prets.loc[prets["ville"] == "TOULOUSE", "benefices"].sum(), 2)

print("---------------------------------------------------------------------------------")
print(f"  Benefice mensuel realiser par l'agence toulousaine : {Benefice_Toulouse} Euros")
print("----------------------------------------------------------------------------------")

---------------------------------------------------------------------------------
  Benefice mensuel realiser par l'agence toulousaine : 2138.07 Euros
----------------------------------------------------------------------------------

## J'ai fait du bon boulot :alors je pense que j'ai une : 6/10