In [1]:
import pandas as pd

In [3]:
df= pd.read_excel("data.xlsx")
df.head()

,Dataset Name,Domain,Source,Country,Data Type,License,Link,Use Cases,Last Updated,Challenges/Notes
0,Common Voice (African Languages),NLP,Mozilla,Africa-wide,Audio,Open Access (CC0 – Public Domain),https://www.mozillafoundation.org/en/common-vo...,"Speech recognition, voice assistants",2024,Requires cleaning for production use
1,KenSwQuAD: Swahili QA Dataset,NLP,Barack W. Wanjawa et al.,Kenya,Text,Public (Via arXiv),https://arxiv.org/abs/2205.02364,"Question answering systems, NLP research",2022,Limited to Swahili; dataset size may be small
2,FLORES+,NLP,Facebook AI /Meta,Africa-wide,Text,Open Access (CC BY-SA 4.0),https://huggingface.co/datasets/openlanguageda...,Evaluating multilingual MT systems,2024,Used in Masakhane benchmarking; supports low-r...
3,Leyu Amharic Speech Dataset,NLP,Leyu.ai,Ethiopia,"Audio, Text",Open Access (CC BY 4.0),https://leyu.ai/datasets,"STT recognition research, regional phonetic mo...",2026,"Mobile-recorded, Crowdsourced valudation focus..."
4,WAXAL collection,NLP,"Makerere University, The University of Ghana, ...",Africa-wide,"Audio, Text",Open Access (CC BY 4.0),https://huggingface.co/datasets/google/WaxalNLP,"Automatic Speech Recognition (ASR), Speech Tra...",2026,"Contains background noise (radio), spontaneous..."

In [4]:
df.shape

(296, 10)

In [6]:
df.isnull().sum()

Dataset Name         0
Domain               0
Source               0
Country              0
Data Type            1
License             33
Link                 9
Use Cases            2
Last Updated         1
Challenges/Notes     4
dtype: int64

In [2]:
data = pd.read_csv("../sang.csv")

In [3]:
data.head()

,donor_id,name,email,password,contact_number,city,blood_group,availability,months_since_first_donation,number_of_donation,pints_donated,created_at
0,1b8b4c828a,Norma Fisher,ysullivan@yahoo.com,P5hX6Syg*A,+61 461706749,Hobart,A+,No,65,31,62,2017-03-17
1,a6a3f7fe55,Eugene Bowman,hramos@brown-sellers.com,b6Wq6Cqz@5,+61 450709944,Darwin,AB-,Yes,64,8,16,2016-11-11
2,cee6478144,Sheri Bolton DDS,jasmine85@hotmail.com,$9RB51m#s7,+61 428756361,Melbourne,AB+,Yes,39,6,6,2022-02-25
3,5986bc55f9,Kelly Boyd,pattylawrence@riley-hayes.com,@5Tdg(4kCm,+61 454318320,Darwin,A-,No,55,20,20,2025-04-04
4,93246afe6c,Taylor Guzman,martinezjacob@wilson.com,x!)9Ag@J*7,+61 484158472,Darwin,O-,No,7,35,35,2022-11-30

In [4]:
data.isnull().sum()

donor_id                       0
name                           0
email                          0
password                       0
contact_number                 0
city                           0
blood_group                    0
availability                   0
months_since_first_donation    0
number_of_donation             0
pints_donated                  0
created_at                     0
dtype: int64

In [1]:
data.shape

NameError: name 'data' is not defined

In [ ]:
donne = pd.read_csv("")